services:
  db:
    image: kartoza/postgis:15-3.4
    container_name: postgres_container
    hostname: ${POSTGRES_HOST}
    environment:
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_PORT=${POSTGRES_PORT}
      - POSTGRES_PASS=${POSTGRES_PASSWORD}
      - POSTGRES_DBNAME=${POSTGRES_DB}
    ports:
      - ${POSTGRES_PORT}:5432
    restart: unless-stopped
    volumes:
      - pg_data:/var/lib/postgresql
      - ./db_init_scripts:/docker-entrypoint-initdb.d
    networks:
      - app_network
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}" ]
      interval: 120s
      timeout: 5s
      retries: 3

  pgadmin:
    image: dpage/pgadmin4:8.11.0
    container_name: pgadmin_container
    environment:
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_PORT=${POSTGRES_PORT}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - PGADMIN_PORT=${PGADMIN_PORT}
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_DEFAULT_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_DEFAULT_PASSWORD}
      - PGADMIN_CONFIG_SERVER_MODE=False
      - PGADMIN_CONFIG_MASTER_PASSWORD_REQUIRED=False
    volumes:
      - ./pgadmin-init.sh:/entrypoint_custom.sh
      - pgadmin_data:/var/lib/pgadmin
    depends_on:
      - db
    user: root
    entrypoint: /entrypoint_custom.sh
    ports:
      - $PGADMIN_PORT:80
    networks:
      - app_network

  api_server:
    env_file:
      - .env
    build:
      context: api_server
      dockerfile: Dockerfile
    image: api_server_image
    container_name: api_server_container
    environment:
      - S3_REGION=${S3_REGION}
      - S3_ENDPOINT=${S3_ENDPOINT}
      - S3_ACCESS_KEY=${S3_ACCESS_KEY}
      - S3_SECRET_KEY=${S3_SECRET_KEY}
      - S3_BUCKET_NAME=${S3_BUCKET_NAME}
      - WORKER_API_KEY=${WORKER_API_KEY}
    ports:
      - ${API_SERVER_PORT}:4000
    volumes:
      - ./api_server:/app
      - ./cli:/cli
    depends_on:
      - db
      - rustfs
    networks:
      - app_network
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:${API_SERVER_PORT}/health", "-H", "accept: application/json", "-H", "Authorization: Bearer ${API_SERVER_KEY}" ]
      interval: 120s
      timeout: 5s
      retries: 3

  nextjs_app:
    environment:
      - NEXT_PUBLIC_PORT=${NEXT_PUBLIC_PORT}
      - API_SERVER_KEY=${API_SERVER_KEY}
      - WATCHPACK_POLLING_INTERVAL=500
      - WATCHPACK_POLLING=true
      - NEXT_PUBLIC_FIREBASE_API_KEY=${NEXT_PUBLIC_FIREBASE_API_KEY}
      - NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN=${NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN}
      - NEXT_PUBLIC_FIREBASE_PROJECT_ID=${NEXT_PUBLIC_FIREBASE_PROJECT_ID}
      - NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET=${NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET}
      - NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID=${NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID}
      - NEXT_PUBLIC_FIREBASE_APP_ID=${NEXT_PUBLIC_FIREBASE_APP_ID}
      - NEXT_PUBLIC_API_SERVER_KEY=${API_SERVER_KEY}
      - NEXT_PUBLIC_MAPBOX_TOKEN=${NEXT_PUBLIC_MAPBOX_TOKEN}
    build:
      context: nextjs_app
      dockerfile: Dockerfile
      args:
        PORT: ${NEXT_PUBLIC_PORT}
    image: nextjs_app_image
    container_name: nextjs
    ports:
      - ${NEXT_PUBLIC_PORT}:${NEXT_PUBLIC_PORT}
    volumes:
      - ./nextjs_app:/app
      - /app/node_modules
      - /app/.next
    depends_on:
      - db
      - api_server
    networks:
      - app_network

  rustfs:
    image: rustfs/rustfs
    container_name: rustfs_container
    ports:
      - "${RUSTFS_PORT1}:${RUSTFS_PORT1}"
      - "${RUSTFS_PORT2}:${RUSTFS_PORT2}"
    volumes:
      - rustfs_data:/data
    environment:
      - RUSTFS_VOLUMES=/data
    networks:
      - app_network
  redis:
    image: redis:alpine
    container_name: redis_container
    ports:
      - "6379:6379"
    networks:
      - app_network

  geopandas_worker:
    build:
      context: geopandas_cli
      dockerfile: Dockerfile
    image: geopandas_worker_image
    container_name: geopandas_worker_container
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - S3_ENDPOINT=${S3_ENDPOINT}
      - S3_ACCESS_KEY=${S3_ACCESS_KEY}
      - S3_SECRET_KEY=${S3_SECRET_KEY}
      - S3_BUCKET_NAME=${S3_BUCKET_NAME}
      - WORKER_API_KEY=${WORKER_API_KEY}
      - API_URL=${API_URL}
    volumes:
      - ./geopandas_cli:/app
    depends_on:
      - redis
    networks:
      - app_network


networks:
  app_network:
    driver: bridge

volumes:
  pg_data:
  pgadmin_data:
  rustfs_data:
  