"use client";
import { useState, useEffect } from "react";
import { X, Upload, Loader2, AlertCircle, FileJson } from "lucide-react";

export default function DatasetUploadModal({
    isOpen,
    onClose,
    onSubmit,
    fileName = "Generated Dataset.geojson",
    defaultDatasetName = "",
    isLoading = false,
    error = null,
    isSuccess = false
}) {
    const [datasetName, setDatasetName] = useState(defaultDatasetName);
    const [datasetDescription, setDatasetDescription] = useState("");

    useEffect(() => {
        if (isOpen) {
            setDatasetName(defaultDatasetName);
            setDatasetDescription("");
        }
    }, [isOpen, defaultDatasetName]);

    const handleSubmit = (e) => {
        e.preventDefault();
        if (!datasetName.trim()) return;
        onSubmit(datasetName.trim(), datasetDescription, false);
    };

    if (!isOpen) return null;

    return (
        <div className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-black/50 backdrop-blur-sm">
            <div className="bg-white rounded-xl shadow-2xl w-full max-w-lg flex flex-col overflow-hidden animate-in fade-in zoom-in-95 duration-200">
                <div className="p-4 border-b border-gray-100 flex items-center justify-between bg-gray-50/50">
                    <h3 className="font-semibold text-gray-900">Upload Generated Dataset</h3>
                    <button
                        onClick={onClose}
                        disabled={isLoading}
                        className="p-2 text-gray-400 hover:text-gray-600 hover:bg-gray-100 rounded-lg transition-colors disabled:opacity-50"
                    >
                        <X className="w-5 h-5" />
                    </button>
                </div>

                <form onSubmit={handleSubmit} className="p-6 space-y-4">
                    <div>
                        <label className="block text-sm font-medium text-gray-700 mb-1">
                            Dataset Name
                        </label>
                        <input
                            type="text"
                            required
                            disabled={isLoading}
                            value={datasetName}
                            onChange={(e) => setDatasetName(e.target.value)}
                            className="w-full px-3 py-2 border border-gray-300 rounded-lg focus:outline-none focus:ring-2 focus:ring-primary/20 focus:border-primary disabled:bg-gray-50 disabled:text-gray-500"
                            placeholder="e.g., Jeddah Universities"
                        />
                    </div>

                    <div>
                        <label className="block text-sm font-medium text-gray-700 mb-1">
                            Description <span className="text-gray-400 font-normal">(Optional)</span>
                        </label>
                        <textarea
                            rows="3"
                            disabled={isLoading}
                            value={datasetDescription}
                            onChange={(e) => setDatasetDescription(e.target.value)}
                            className="w-full px-3 py-2 border border-gray-300 rounded-lg focus:outline-none focus:ring-2 focus:ring-primary/20 focus:border-primary disabled:bg-gray-50 disabled:text-gray-500"
                            placeholder="Add a description for this dataset..."
                        />
                    </div>

                    <div>
                        <label className="block text-sm font-medium text-gray-700 mb-1">
                            File to Upload
                        </label>
                        <div className="mt-1 flex justify-center px-6 pt-5 pb-6 border-2 border-dashed border-gray-300 rounded-lg bg-gray-50">
                            <div className="space-y-1 text-center w-full">
                                <div className="mt-2 p-3 bg-primary/5 rounded-lg border border-primary/10 flex items-center gap-3">
                                    <FileJson className="w-6 h-6 text-primary shrink-0" />
                                    <div className="flex flex-col items-start overflow-hidden w-full">
                                        <span className="text-sm text-primary font-medium truncate w-full text-left">
                                            {fileName}
                                        </span>
                                        <span className="text-xs text-gray-500">
                                            Generated by AI
                                        </span>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>

                    {error && (
                        <div className="p-3 bg-red-50 text-red-600 text-sm rounded-lg flex items-start gap-2">
                            <AlertCircle className="w-4 h-4 mt-0.5 shrink-0" />
                            <span>{error}</span>
                        </div>
                    )}

                    {isSuccess && (
                        <div className="p-3 bg-green-50 text-green-600 text-sm rounded-lg flex items-center gap-2">
                            <div className="w-2 h-2 bg-green-500 rounded-full" />
                            <span>Dataset uploaded successfully!</span>
                        </div>
                    )}

                    <div className="pt-2 flex justify-end gap-3">
                        <button
                            type="button"
                            onClick={onClose}
                            disabled={isLoading}
                            className="px-4 py-2 text-sm font-medium text-gray-700 hover:bg-gray-100 rounded-lg transition-colors disabled:opacity-50"
                        >
                            Cancel
                        </button>
                        <button
                            type="submit"
                            disabled={!datasetName.trim() || isLoading || isSuccess}
                            className="px-4 py-2 text-sm font-medium text-white bg-primary hover:bg-primary/90 rounded-lg transition-colors disabled:opacity-50 disabled:cursor-not-allowed flex items-center gap-2"
                        >
                            {isLoading && <Loader2 className="w-4 h-4 animate-spin" />}
                            {isLoading ? "Uploading..." : "Upload Dataset"}
                        </button>
                    </div>
                </form>
            </div>
        </div>
    );
}
