"use client";

import React, { useState, useEffect, useRef } from "react";
import { useAuth } from "@/hooks/useAuth";
import { useSelector } from "react-redux";
import { selectActiveProject } from "@/lib/store/features/projectSlice";
import { Button } from "@/components/ui/button";
import { Send, Bot, User, Loader2, MapPin, Download, Upload } from "lucide-react";
import ChatLeafletMap from "@/components/ChatLeafletMap";
import DatasetUploadModal from "@/components/DatasetUploadModal";
import { uploadFile } from '@/lib/uploadApi';

export default function ChatPage() {
    const { user } = useAuth();
    const activeProject = useSelector(selectActiveProject);
    const [messages, setMessages] = useState([]);
    const [input, setInput] = useState("");
    const [loading, setLoading] = useState(false);
    const [sessionId, setSessionId] = useState(null);
    const [jobPolling, setJobPolling] = useState(false);
    const [selectedGeojson, setSelectedGeojson] = useState(null);
    const [uploadModalOpen, setUploadModalOpen] = useState(false);
    const [uploadGeojson, setUploadGeojson] = useState(null);
    const [isUploading, setIsUploading] = useState(false);
    const [uploadError, setUploadError] = useState(null);
    const [uploadSuccess, setUploadSuccess] = useState(false);
    const messagesEndRef = useRef(null);

    const handleDownload = (geojson, toolName) => {
        const blob = new Blob([JSON.stringify(geojson, null, 2)], { type: "application/json" });
        const url = URL.createObjectURL(blob);
        const a = document.createElement("a");
        a.href = url;
        a.download = `${toolName || "dataset"}_export.geojson`;
        a.click();
        URL.revokeObjectURL(url);
    };

    const handleUploadSubmit = async (datasetName, datasetDescription) => {
        if (!uploadGeojson || !activeProject) return;
        setIsUploading(true);
        setUploadError(null);
        
        try {
            const blob = new Blob([JSON.stringify(uploadGeojson)], { type: 'application/json' });
            const file = new File([blob], `${datasetName.replace(/\s+/g, '_')}.geojson`, { type: 'application/json' });
            
            await uploadFile({
                file: file,
                isPrivate: true,
                projectId: activeProject?.id,
                layerName: datasetName,
                description: datasetDescription || `Generated by AI Chat.`
            });
            
            setUploadSuccess(true);
            setTimeout(() => {
                setUploadModalOpen(false);
                setUploadGeojson(null);
                setUploadSuccess(false);
            }, 1000);
        } catch (error) {
            setUploadError(error.message || 'Upload failed');
        } finally {
            setIsUploading(false);
        }
    };

    const scrollToBottom = () => {
        messagesEndRef.current?.scrollIntoView({ behavior: "smooth" });
    };

    useEffect(() => {
        scrollToBottom();
    }, [messages, loading]);

    useEffect(() => {
        if (activeProject && user) {
            loadHistory();
        }
    }, [activeProject, user]);

    useEffect(() => {
        let interval;
        if (jobPolling && sessionId) {
            interval = setInterval(async () => {
                const token = await user?.getIdToken();
                const res = await fetch(`${process.env.NEXT_PUBLIC_API_URL}/chat/job-status/${sessionId}`, {
                    headers: { Authorization: `Bearer ${token}` }
                });
                const data = await res.json();
                if (!data.activeJobs) {
                    setJobPolling(false);
                    loadHistory();
                }
            }, 3000);
        }
        return () => clearInterval(interval);
    }, [jobPolling, sessionId, user]);

    const loadHistory = async () => {
        try {
            const token = await user?.getIdToken();
            const res = await fetch(`${process.env.NEXT_PUBLIC_API_URL}/chat/${activeProject.id}`, {
                headers: { Authorization: `Bearer ${token}` }
            });
            const data = await res.json();
            if (data.success) {
                setMessages(data.messages);
                if (data.sessionId) setSessionId(data.sessionId);
                
                // Auto-select latest geojson for map if available
                const latestToolMsg = data.messages.slice().reverse().find(m => m.role === 'tool' && m.tool_calls?.data);
                if (latestToolMsg) {
                    setSelectedGeojson(latestToolMsg.tool_calls.data);
                }
            }
        } catch (error) {
            console.error("Failed to load chat history", error);
        }
    };

    const handleSend = async (e) => {
        e.preventDefault();
        if (!input.trim() || !activeProject) return;

        const userMsg = { role: "user", content: input };
        setMessages((prev) => [...prev, userMsg]);
        setInput("");
        setLoading(true);

        try {
            const token = await user?.getIdToken();
            const response = await fetch(`${process.env.NEXT_PUBLIC_API_URL}/chat/${activeProject.id}/message`, {
                method: "POST",
                headers: {
                    "Content-Type": "application/json",
                    Authorization: `Bearer ${token}`
                },
                body: JSON.stringify({ content: userMsg.content })
            });

            if (!response.ok) throw new Error("Failed to send message");

            const reader = response.body.getReader();
            const decoder = new TextDecoder("utf-8");

            let assistantMsg = { role: "assistant", content: "" };
            setMessages((prev) => [...prev, assistantMsg]);

            while (true) {
                const { done, value } = await reader.read();
                if (done) break;

                const chunk = decoder.decode(value, { stream: true });
                const lines = chunk.split('\n').filter(line => line.trim().startsWith('data: '));

                for (const line of lines) {
                    const dataStr = line.replace(/^data: /, '').trim();
                    if (dataStr === '[DONE]') continue;

                    try {
                        const data = JSON.parse(dataStr);
                        if (data.content) {
                            assistantMsg.content += data.content;
                            setMessages((prev) => {
                                const newMessages = [...prev];
                                newMessages[newMessages.length - 1] = { ...assistantMsg };
                                return newMessages;
                            });
                        }
                        if (data.tool_call) {
                            setJobPolling(true);
                            setTimeout(loadHistory, 500);
                        }
                    } catch (e) { }
                }
            }

        } catch (error) {
            console.error("Chat error:", error);
        } finally {
            setLoading(false);
        }
    };

    if (!activeProject) {
        return <div className="p-8 text-center text-muted-foreground">Please select a project first.</div>;
    }

    return (
        <div className="flex flex-col lg:flex-row h-[calc(100vh-60px)] md:h-[calc(100vh-20px)] bg-gray-50/50 relative w-full overflow-hidden">
            {/* Chat Container */}
            <div className="flex flex-col h-full lg:w-1/2 shrink-0 border-r bg-white shadow-xl z-20">
                <div className="border-b bg-white px-6 py-4 flex items-center shadow-sm w-full shrink-0">
                    <Bot className="w-5 h-5 text-primary me-2" />
                    <h1 className="text-xl font-semibold">Project AI Assistant</h1>
                </div>

                <div className="flex-1 overflow-y-auto p-4 md:p-6 space-y-6">
                {messages.length === 0 && (
                    <div className="h-full flex flex-col items-center justify-center text-center space-y-4 max-w-md mx-auto">
                        <div className="size-16 rounded-2xl bg-primary/10 flex items-center justify-center text-primary">
                            <Bot className="size-8" />
                        </div>
                        <h2 className="text-2xl font-bold text-gray-900">How can I help you?</h2>
                        <p className="text-muted-foreground text-sm">
                            I can answer questions and use tools to find points of interest. 
                            Just ask me to "Find hospitals in Jeddah".
                        </p>
                    </div>
                )}

                {messages.map((msg, i) => (
                    <div key={i} className={`flex gap-4 max-w-3xl ${msg.role === 'user' ? 'ms-auto flex-row-reverse' : ''}`}>
                        <div className={`shrink-0 size-8 rounded-full flex items-center justify-center ${msg.role === 'user' ? 'bg-primary text-white' : msg.role === 'tool' ? 'bg-green-100 text-green-700' : 'bg-blue-100 text-blue-700'}`}>
                            {msg.role === 'user' ? <User className="size-4" /> : msg.role === 'tool' ? <MapPin className="size-4" /> : <Bot className="size-4" />}
                        </div>
                        <div className={`flex flex-col gap-1 ${msg.role === 'user' ? 'items-end' : 'items-start'} max-w-[80%]`}>
                            <div className={`px-4 py-3 rounded-2xl text-sm whitespace-pre-wrap ${
                                msg.role === 'user' 
                                ? 'bg-primary text-white rounded-tr-sm' 
                                : msg.role === 'tool'
                                ? 'bg-white border-2 border-green-200 shadow-sm rounded-tl-sm w-full'
                                : 'bg-white border shadow-sm rounded-tl-sm'
                            }`}>
                                {msg.content}
                                {msg.tool_calls && !msg.tool_calls.data && (
                                    <div className="mt-3 p-3 bg-gray-50 rounded-lg border text-xs text-gray-500 font-mono overflow-auto max-h-[300px] max-w-[600px] scrollbar-thin">
                                        <pre>{JSON.stringify(msg.tool_calls, null, 2)}</pre>
                                    </div>
                                )}
                                {msg.tool_calls?.data && (
                                    <div className="mt-3 flex flex-wrap gap-2">
                                        <Button 
                                            size="sm" 
                                            variant="outline" 
                                            className="h-8 text-xs bg-white hidden lg:flex"
                                            onClick={() => setSelectedGeojson(msg.tool_calls.data)}
                                        >
                                            <MapPin className="size-3 mr-1" /> View on Map
                                        </Button>
                                        <Button 
                                            size="sm" 
                                            variant="outline" 
                                            className="h-8 text-xs bg-white"
                                            onClick={() => handleDownload(msg.tool_calls.data, msg.tool_calls.tool_name)}
                                        >
                                            <Download className="size-3 mr-1" /> Download
                                        </Button>
                                        <Button 
                                            size="sm" 
                                            variant="default" 
                                            className="h-8 text-xs"
                                            onClick={() => {
                                                setUploadGeojson(msg.tool_calls.data);
                                                setUploadSuccess(false);
                                                setUploadError(null);
                                                setUploadModalOpen(true);
                                            }}
                                        >
                                            <Upload className="size-3 mr-1" /> Upload to Project
                                        </Button>
                                    </div>
                                )}
                            </div>
                        </div>
                    </div>
                ))}
                
                {jobPolling && (
                    <div className="flex gap-4 max-w-3xl">
                        <div className="shrink-0 size-8 rounded-full bg-blue-100 text-blue-700 flex items-center justify-center">
                            <Loader2 className="size-4 animate-spin" />
                        </div>
                        <div className="px-4 py-3 rounded-2xl text-sm bg-white border shadow-sm rounded-tl-sm text-muted-foreground flex items-center gap-2">
                            Executing tool... This may take a minute.
                        </div>
                    </div>
                )}
                <div ref={messagesEndRef} />
            </div>

                <div className="bg-white border-t p-4 shadow-[0_-10px_40px_-15px_rgba(0,0,0,0.05)] w-full shrink-0">
                    <form onSubmit={handleSend} className="max-w-4xl mx-auto flex gap-3 items-end">
                        <div className="flex-1 relative">
                            <textarea
                                value={input}
                                onChange={(e) => setInput(e.target.value)}
                                onKeyDown={(e) => {
                                    if (e.key === 'Enter' && !e.shiftKey) {
                                        e.preventDefault();
                                        handleSend(e);
                                    }
                                }}
                                placeholder="Message AI Assistant..."
                                className="w-full min-h-[50px] max-h-[150px] bg-gray-100 border-none rounded-2xl px-5 py-3.5 pr-14 text-sm focus:ring-2 focus:ring-primary/20 resize-none shadow-inner"
                                rows={1}
                            />
                        </div>
                        <Button 
                            type="submit" 
                            size="icon"
                            className="size-12 rounded-full shrink-0 shadow-md" 
                            disabled={loading || !input.trim()}
                        >
                            {loading && !jobPolling ? <Loader2 className="size-5 animate-spin" /> : <Send className="size-5 ms-1" />}
                        </Button>
                    </form>
                </div>
            </div>

            {/* Map Container (Hidden on small screens) */}
            <div className="hidden lg:flex flex-1 relative bg-gray-100 z-10 h-full">
                {selectedGeojson ? (
                    <ChatLeafletMap 
                        geojson={selectedGeojson} 
                        className="w-full h-full"
                    />
                ) : (
                    <div className="flex w-full h-full items-center justify-center text-gray-400">
                        <div className="text-center">
                            <MapPin className="size-12 mx-auto mb-4 opacity-50" />
                            <p>Map visualization will appear here.</p>
                        </div>
                    </div>
                )}
            </div>

            <DatasetUploadModal 
                isOpen={uploadModalOpen}
                onClose={() => setUploadModalOpen(false)}
                onSubmit={handleUploadSubmit}
                isLoading={isUploading}
                error={uploadError}
                isSuccess={uploadSuccess}
                fileName="Generated Dataset.geojson"
                defaultDatasetName="AI Export"
            />
        </div>
    );
}
