import os

API_SERVER_URL = os.getenv("API_SERVER_URL", "http://api_server:4000")

PRIMARY_LLM_BASE_URL = os.getenv("PRIMARY_LLM_BASE_URL", "http://host.docker.internal:1234/v1")
PRIMARY_LLM_MODEL = os.getenv("PRIMARY_LLM_MODEL", "qwen3.5-9b")
PRIMARY_LLM_API_KEY = os.getenv("PRIMARY_LLM_API_KEY", "lm-studio")

VERIFIER_LLM_BASE_URL = os.getenv("VERIFIER_LLM_BASE_URL", PRIMARY_LLM_BASE_URL)
VERIFIER_LLM_MODEL = os.getenv("VERIFIER_LLM_MODEL", PRIMARY_LLM_MODEL)
VERIFIER_LLM_API_KEY = os.getenv("VERIFIER_LLM_API_KEY", PRIMARY_LLM_API_KEY)

MAX_FEATURES_IN_CONTEXT = int(os.getenv("MAX_FEATURES_IN_CONTEXT", "200"))
LLM_TEMPERATURE = float(os.getenv("LLM_TEMPERATURE", "0.1"))
LLM_TIMEOUT_SECONDS = float(os.getenv("LLM_TIMEOUT_SECONDS", "120"))
